apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: weather-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: kondapallitarun3474/weather-auth:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: app-data
          mountPath: /app/users.json
          subPath: users.json
      initContainers:
      - name: init-users
        image: busybox
        # Check if users.json exists in PVC. Only copy if MISSING.
        command: ["sh", "-c", "if [ ! -f /data/users.json ]; then echo 'Initializing users.json from ConfigMap...'; cp /config/users.json /data/users.json; else echo 'users.json already exists in PVC. Skipping init.'; fi"]
        volumeMounts:
        - name: users-config
          mountPath: /config
        - name: app-data
          mountPath: /data
      volumes:
      - name: users-config
        configMap:
          name: auth-users-config
      - name: app-data
        persistentVolumeClaim:
          claimName: auth-data-pvc
