---
apiVersion: v1
kind: Service
metadata:
  name: inference-t2m-service
  namespace: weather-mlops
spec:
  selector:
    app: inference-t2m
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: inference-rh2m-service
  namespace: weather-mlops
spec:
  selector:
    app: inference-rh2m
  type: NodePort
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5001
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: inference-ws2m-service
  namespace: weather-mlops
spec:
  selector:
    app: inference-ws2m
  type: NodePort
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5001
      nodePort: 30003
